name: DocsCI
on:
  push:
    branches:
      - docs
env:
  TZ: Asia/Beijing # 设置当前环境时区
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install --upgrade pip
      - run: pip install mkdocs-material
      - run: pip install jieba
      - run: pip install mike
      - run: pip install git-revision-date-localized
      - run: mkdocs gh-deploy --force
